### ISSUE TITLE
Authenticated user error

### ISSUE THREAD

**Issue by makkus** [openresearchdata/ckanext-oaipmh#15]
I just gave this extension a spin to import datasets from our dspace instance, it seems to connect fine, but I'm getting an error related to user authentication when it tries to create groups on the local ckan instance (it seems to me, anyway):

===================

2015-07-06 04:11:28,544 DEBUG [ckanext.oaipmh.harvester] URL of ressource: http://hdl.handle.net/123456789/1277
2015-07-06 04:11:28,544 DEBUG [ckanext.oaipmh.harvester] set_spec: [u'com_123456789_5', u'col_123456789_1275']
2015-07-06 04:11:28,544 DEBUG [ckanext.oaipmh.harvester] Group names: [u'com_123456789_5', u'col_123456789_1275']
2015-07-06 04:11:28,560 ERROR [ckanext.oaipmh.harvester] Something went wrong!
Traceback (most recent call last):
  File "/project/ckanext-oaipmh/ckanext/oaipmh/harvester.py", line 292, in import_stage
    context
  File "/project/ckanext-oaipmh/ckanext/oaipmh/harvester.py", line 423, in _find_or_create_groups
    group = get_action('group_create')(context, data_dict)
  File "/project/ckan/ckan/logic/__init__.py", line 424, in wrapped
    result = _action(context, data_dict, **kw)
  File "/project/ckan/ckan/logic/action/create.py", line 856, in group_create
    _check_access('group_create', context, data_dict)
  File "/project/ckan/ckan/logic/__init__.py", line 294, in check_access
    raise NotAuthorized(msg)
NotAuthorized: <function group_create at 0x7f876e50bb90> requires an authenticated user
2015-07-06 04:11:28,569 DEBUG [ckanext.harvest.harvesters.base] Exception in import stage

===================

Any idea what I'm doing wrong?

**Comment by metaodi** [comment]
@makkus Do you have an admin user called "harvest"? This is the default user that currently all harvesters based on ckanext-harvest use.

**Comment by makkus** [comment]
Ah, right. No, wasn't aware of that. Thanks!
